### PR TITLE
Add Media advisory support (Label: SA)

### PR DESCRIPTION
**Pull request by fcrohas**
Hi,
   This is first part with only Media advisory message.
   I hope code is like it should.

### CODE REVIEW

**Comment by szpajder** [comment]
Yes, the structure is good. Just a few small issues:

- Windows does not have `strptime()`, so it fails to compile with mingw. But this function is not absolutely needed here. Just copying the digits into three char buffers: hour, min, sec will be fine.

- If the message version is different than 0, then I would not bother parsing it any further. If there will ever be a version 1 or 2 or 3, we have no guarantee that the syntax will be the same as for version 0 - if it will differ, then the parser will do strange things and may even crash. So if version != 0 then set the err flag and format the result as "-- Unparseable media advisory message" (like ADS-C and CPDLC formatters do it). Of course the version will be 0 in 99.99% of cases, but better safe than sorry. For checking conditions which are almost always true or almost always false we have `LA_LIKELY()` and `LA_UNLIKELY()` macros in `macros.h`.

- Basic sanity checking of the message contents - the second character must always be 'E' or 'L'. Timestamp must be all digits. Link types must be valid (otherwise a nasty `(null)` appears in the output).

- if you don't need `msg_dir` in `la_media_adv_parse()`, then you can simply remove this argument. Parsers are invoked directly (not via function pointers), so their prototypes are not required to be the same.

- Not really an error, but I'm just curious - why `la_media_adv_link_type_map` has `char const code[1]` instead of just `char const code`?

But of course thanks for your effort. Don't let my grumbles discourage you :-)

**Comment by fcrohas** [comment]
Ok thanks for your remark, pull request are there for this ! The same at office :)
What about my hack with LA_ISPRINTF and empty argument , i was using vstrung append buffer, but indent was not here ...

**Comment by szpajder** [comment]
Merged, thanks.

About `LA_ISPRINTF()` - hm, nope, it's not the way it works. `la_isprintf_append_sprintf()` appends a formatted string to a given `la_vstring`. `LA_ISPRINTF()` means "indented sprintf()" - it indents the formatted string with `indent` spaces and appends the result to a given `la_vstring`. Essentially it's just a wrapper for `la_vstring_append_sprintf()` and its only purpose is to improve code readability. So when you start a new line of the output and want it indented, use `LA_ISPRINTF()`, but when you continue the output on the same line (like in the loop which prints all available links), use `la_vstring_append_sprintf()` directly. Otherwise you wll get extra spaces in the middle of the line.

The output convention in libacars is that the message fields are indented one level deeper than its header. That is, after printing `"Media Advisory version 0:\n"` you should increment `indent`. I've already corrected this and also applied a few minor fixes, so just pull my unstable branch to get in sync.

And please, please do not overwrite history entries when you modify the code for which you've already submitted a pull request. If you want to fix or change something before I merge the request, then just add new commits to your unstable branch and drop me a comment here to let me know that there is something new I should deal with. It's enough when the new commits exist only in your unstable branch, you don't need to resubmit the request. For example, the original commit that you have submitted with this pull request (https://github.com/fcrohas/libacars/commit/a453725498bf5e3d9979c5da019c0e2a5ccb35cd) is no longer available in the history of your unstable branch. There is only the new commit (https://github.com/fcrohas/libacars/commit/ec0d0c2ab707014498d0ed945513ee7919a4d5a7) which reimplements the whole thing from scratch. This makes things harder for me, because I can't just pull your branch again to get it in sync - I have to delete my copy of it and start from scratch. It's also more difficult to figure out what has changed between the first version of the code and the second one. So instead of overwriting the previous version, just add a new commit with the fixes and I'll be able to merge it easily.

**Comment by fcrohas** [comment]
Ok for the pull request, i will do that to keep only one commit to merge for you and have a clean history. Next time i will fix with more commit no problem.
I think you asked me one commit on dumpvdl2 a year before.

Thanks i continue, I will add the rest later

**Pull request merged**
